### ISSUE TITLE
教育訓練 - 參考手冊實際操作 TWCC

### ISSUE THREAD

**Issue by VigaWei** [twcc/TWCC-Docs-en#4]
### To-do:

- 請參考以下三份手冊，按照優先順序，實際操作、了解 TWCC 服務的資訊 👀
- 閱讀完 or 操作完的手冊的請在下方 ✅ 
- 未列入的手冊，以下操作完再參考即可~
- 本週看不完沒關係 🙆 
- 如果有發現文件 bug，請回報在 issue (請附上文件 link、說明、截圖)，謝謝! 🐞 
-  ❓ 不太懂的部分歡迎到 Slack 發問
-  ❗ **特別注意!! 兩位在維運計畫中的身份是租戶管理員，<ins>TWCC 上請小心操作，勿刪除或調整其他成員的資源</ins>** ❗ 

### Docs:

<details><summary>1. <a href="https://man.twcc.ai/@twccdocs/doc-service-main-zh">TWCC 會員/計畫/帳務</a> (點開優先順序)</summary>

- 使用指南：
    1. 註冊帳號
    2. 進入會員系統
    3. 查詢主機帳號、重置密碼與取得 OTP 認證碼
    4. API 金鑰
    5. 資源配額管理
    6. 管理計畫成員
    7. 檢視計畫資訊
    8. 解決手機收不到簡訊驗證碼

- 其他資訊：
    1. FAQ (會員計畫與帳務/產品概觀/使用者網站) 
 </details>

<details><summary>2. <a href="https://man.twcc.ai/@twccdocs/doc-ccs-main-zh">開發型容器</a> (點開優先順序)</summary>

- 使用指南：
    1. 服務概觀
    2. 建立、連線、管理、監控容器
    3. 高速檔案系統
    4. 雲端物件儲存
    5. 連接埠
    6. 複本

- 案例教學：
    1. 使用 TensorFlow Inception V3 訓練影像辨識模型、生成推論引擎
    2. 使用 TensorFlow 訓練 MNIST 手寫數字辨識模型
    3. 檢視運算資源概況－GPU Burn Testing
    4. 設定開發型容器的服務埠
    5. 自動完成運算及刪除容器
    6. 部署自動化 AI/ML pipeline
    7. Python 套件安裝指南

- 其他資訊：
    1. FAQ (CCS)
    2. 價目表 (CCS)

</details>

<details><summary>3. <a href="https://man.twcc.ai/@twccdocs/doc-vcs-main-zh">虛擬運算服務</a> (點開優先順序)</summary>

- 使用指南：
  1. 服務概觀
  2. 建立虛擬運算個體
  3. 建立與管理鑰匙對
  4. 準備工作
  5. 連線至 Linux 個體
  6. 連線至 Windows 個體
  7. 檢視/編輯
  8. 停止/啟動/關機/重開機/刪除
  9. 監控
  10. (備份個體)建立映像檔
  11. 建立映像檔最佳作法
  12. 管理映像檔
  13. 建立客製化個體
  14. 建立資料磁碟
  15. 檢視/連結/刪除 資料磁碟
  16. 分離資料磁碟
  17. 備份磁碟
  18. 負載平衡
  19. Auto Scaling
  20. 安全性群組
        
- 案例教學
  1. 初始化磁碟- Linux
  2. 初始化磁碟- Windows
  3. 架設安全、可負載高流量的網站
  4. 使用一台虛擬運算個體架設多個且安全的網站
 
 - 概念說明
   1. 個體生命週期

- 其他資訊
  1. FAQ (VCS)
  2. 價目表 (VCS) 
</details>

**Comment by VigaWei** [comment]
## For Betty:

#### 1. [TWCC 會員/計畫/帳務](https://man.twcc.ai/@twccdocs/doc-service-main-zh)，優先順序：
- 使用指南：
    1. [ ] 註冊帳號
    2. [ ] 進入會員系統
    3. [ ] 查詢主機帳號、重置密碼與取得 OTP 認證碼
    4. [ ] API 金鑰
    5. [ ] 資源配額管理
    6. [ ] 管理計畫成員
    7. [ ] 檢視計畫資訊
    8. [ ] 解決手機收不到簡訊驗證碼

- 其他資訊：
    1. [ ] FAQ (會員計畫與帳務/產品概觀/使用者網站) 

#### 2. [開發型容器](https://man.twcc.ai/@twccdocs/doc-ccs-main-zh)，優先順序：

- 使用指南：
    1. [ ] 服務概觀
    2. [ ] 建立、連線、管理、監控容器
    3. [ ] 高速檔案系統
    4. [ ] 雲端物件儲存
    5. [ ] 連接埠
    6. [ ] 複本

- 案例教學：
    1. [ ] 使用 TensorFlow Inception V3 訓練影像辨識模型、生成推論引擎
    2. [ ] 使用 TensorFlow 訓練 MNIST 手寫數字辨識模型
    3. [ ] 檢視運算資源概況－GPU Burn Testing
    4. [ ] 設定開發型容器的服務埠
    5. [ ] 自動完成運算及刪除容器
    6. [ ] 部署自動化 AI/ML pipeline
    7. [ ] Python 套件安裝指南

- 其他資訊：
    1. [ ] FAQ (CCS)
    2. [ ] 價目表 (CCS)


#### 3. [虛擬運算服務](https://man.twcc.ai/@twccdocs/doc-vcs-main-zh)，優先順序：
- 使用指南：
  1. [ ] 服務概觀
  2. [ ] 建立虛擬運算個體
  3. [ ] 建立與管理鑰匙對
  4. [ ] 準備工作
  5. [ ] 連線至 Linux 個體
  6. [ ] 連線至 Windows 個體
  7. [ ] 檢視/編輯
  8. [ ] 停止/啟動/關機/重開機/刪除
  9. [ ] 監控
  10. [ ] (備份個體)建立映像檔
  11. [ ] 建立映像檔最佳作法
  12. [ ] 管理映像檔
  13. [ ] 建立客製化個體
  14. [ ] 建立資料磁碟
  15. [ ] 檢視/連結/刪除 資料磁碟
  16. [ ] 分離資料磁碟
  17. [ ] 備份磁碟
  18. [ ] 負載平衡
  19. [ ] Auto Scaling
  20. [ ] 安全性群組
        
- 案例教學
  1. [ ] 初始化磁碟- Linux
  2. [ ] 初始化磁碟- Windows
  3. [ ] 架設安全、可負載高流量的網站
  4. [ ] 使用一台虛擬運算個體架設多個且安全的網站
 
 - 概念說明
   1. [ ] 個體生命週期

- 其他資訊
  1. [ ] FAQ (VCS)
  2. [ ] 價目表 (VCS)

**Comment by VigaWei** [comment]
## For Sing:

#### 1. [TWCC 會員/計畫/帳務](https://man.twcc.ai/@twccdocs/doc-service-main-zh)，優先順序：
- 使用指南：
    1. [ ] 註冊帳號
    2. [ ] 進入會員系統
    3. [ ] 查詢主機帳號、重置密碼與取得 OTP 認證碼
    4. [ ] API 金鑰
    5. [ ] 資源配額管理
    6. [ ] 管理計畫成員
    7. [ ] 檢視計畫資訊
    8. [ ] 解決手機收不到簡訊驗證碼

- 其他資訊：
    1. [ ] FAQ (會員計畫與帳務/產品概觀/使用者網站) 

#### 2. [開發型容器](https://man.twcc.ai/@twccdocs/doc-ccs-main-zh)，優先順序：

- 使用指南：
    1. [ ] 服務概觀
    2. [ ] 建立、連線、管理、監控容器
    3. [ ] 高速檔案系統
    4. [ ] 雲端物件儲存
    5. [ ] 連接埠
    6. [ ] 複本

- 案例教學：
    1. [ ] 使用 TensorFlow Inception V3 訓練影像辨識模型、生成推論引擎
    2. [ ] 使用 TensorFlow 訓練 MNIST 手寫數字辨識模型
    3. [ ] 檢視運算資源概況－GPU Burn Testing
    4. [ ] 設定開發型容器的服務埠
    5. [ ] 自動完成運算及刪除容器
    6. [ ] 部署自動化 AI/ML pipeline
    7. [ ] Python 套件安裝指南

- 其他資訊：
    1. [ ] FAQ (CCS)
    2. [ ] 價目表 (CCS)


#### 3. [虛擬運算服務](https://man.twcc.ai/@twccdocs/doc-vcs-main-zh)，優先順序：
- 使用指南：
  1. [ ] 服務概觀
  2. [ ] 建立虛擬運算個體
  3. [ ] 建立與管理鑰匙對
  4. [ ] 準備工作
  5. [ ] 連線至 Linux 個體
  6. [ ] 連線至 Windows 個體
  7. [ ] 檢視/編輯
  8. [ ] 停止/啟動/關機/重開機/刪除
  9. [ ] 監控
  10. [ ] (備份個體)建立映像檔
  11. [ ] 建立映像檔最佳作法
  12. [ ] 管理映像檔
  13. [ ] 建立客製化個體
  14. [ ] 建立資料磁碟
  15. [ ] 檢視/連結/刪除 資料磁碟
  16. [ ] 分離資料磁碟
  17. [ ] 備份磁碟
  18. [ ] 負載平衡
  19. [ ] Auto Scaling
  20. [ ] 安全性群組
        
- 案例教學
  1. [ ] 初始化磁碟- Linux
  2. [ ] 初始化磁碟- Windows
  3. [ ] 架設安全、可負載高流量的網站
  4. [ ] 使用一台虛擬運算個體架設多個且安全的網站
 
 - 概念說明
   1. [ ] 個體生命週期

- 其他資訊
  1. [ ] FAQ (VCS)
  2. [ ] 價目表 (VCS)

**Comment by cxheng315** [comment]
開發型容器[連結](https://man.twcc.ai/@twccdocs/doc-ccs-main-zh/%2F%40twccdocs%2Fguide-ccs-create-zh#%E5%BB%BA%E7%AB%8B%E9%96%8B%E7%99%BC%E5%9E%8B%E5%AE%B9%E5%99%A81) TWCC CLI 下拉選項
出現“HackMD Error: 404 Not Found”錯誤，推測應該是"{%hackmd @twccdocs/cli-optional-note-zh %}"  
有嘗試在hackmd中尋找這份文件，但沒找到相關的。
![image](https://user-images.githubusercontent.com/64959125/127553869-5484a31b-248a-466b-82b5-28bbcc95a2f7.png)

**Comment by VigaWei** [comment]
> 開發型容器[連結](https://man.twcc.ai/@twccdocs/doc-ccs-main-zh/%2F%40twccdocs%2Fguide-ccs-create-zh#%E5%BB%BA%E7%AB%8B%E9%96%8B%E7%99%BC%E5%9E%8B%E5%AE%B9%E5%99%A81) TWCC CLI 下拉選項
> 出現“HackMD Error: 404 Not Found”錯誤，推測應該是"{%hackmd @twccdocs/cli-optional-note-zh %}"
> 有嘗試在hackmd中尋找這份文件，但沒找到相關的。
> ![image](https://user-images.githubusercontent.com/64959125/127553869-5484a31b-248a-466b-82b5-28bbcc95a2f7.png)

**Comment by twsc-aug** [comment]
that only works in man.twcc.ai

**Comment by ting88510** [comment]
開發型容器的[設定開發型容器的服務埠](https://man.twcc.ai/@twccdocs/doc-ccs-main-zh/https%3A%2F%2Fman.twcc.ai%2F%40twccdocs%2Fhowto-ccs-config-service-port-zh)
下載並執行腳本內容的部分會報錯
<img width="1440" alt="截圖 2021-07-29 下午11 12 49" src="https://user-images.githubusercontent.com/46339898/127593177-97fe4716-396d-468e-aff4-ffda462f4254.png">

**Comment by twsc-aug** [comment]
https://bit.ly/TWCC_TestServicePort_5002 link 壞掉了~~ 
待補
